[book]
title = "JioTV"
authors = ["JioTV contributors"]
language = "en"
src = "."

[output.html]
site-url = "/better-jiotv-go/"
git-repository-url = "https://github.com/wpfyorg/better-jiotv-go"
edit-url-template = "https://github.com/wpfyorg/better-jiotv-go/edit/main/docs/{path}"
default-theme = "navy"
preferred-dark-theme = "navy"

[output.html.search]
enable = true
